CFLAGS=-Wall -g
all: ex1 ex3 ex9 ex17 ex18
ex1: ex1.c
	gcc -o ex1 ex1.c
ex3: ex3.c
	gcc -o ex3 ex3.c
ex9: ex9.c
	gcc -o ex9 ex9.c
ex17: ex17.c
	gcc -o ex9 ex9.c
ex18: ex18.c
	gcc -o ex18 ex18.c
clean:
	rm -f ex1
	rm -f ex3
	rm -f ex9
	rm -f ex17
	rm -f ex18
